language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby
sudo: false
before_install:
  - gem update system
  - gem install bundler
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: 2.5